services:
  mariadb:
    image: mariadb:lts-ubi
    container_name: mariadb-roomsy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: roomsydb
    ports:
      - "3306:3306"
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge

